### ISSUE TITLE
ev3_dc import error

### ISSUE THREAD

**Issue by Safacan7** [ChristophGaukel/ev3-python3#13]
![image](https://user-images.githubusercontent.com/83445170/156317161-c221a776-1967-4839-a46c-2aae5fbf95c6.png)
Hi, I am trying to build Rubik's cube solver using Lego Mindstorm Ev3, however, I am facing this import error.
I have followed the instructions and installed ev3_dc using the below command,
**python3 -m pip install --user ev3_dc**

I deleted all my other python versions to prevent any mix-up of dependencies, I have also tried creating a virtual environment to solve this issue. I am using windows 10, however, I have tried using ubuntu to solve this issue but it still did not work.

**Comment by ChristophGaukel** [comment]
Hi,
brickrun is a tool, which loads python programs to the EV3 brick and starts them under ev3dev. ev3dev does not support direct commands. Therefore ev3_dc and ev3dev are not compatible. Please shutdown your EV3 brick, extract your ev3dev SD-card, then restart your EV3 brick. Then do these steps (on your computer in the terminal cmd shell):

1. navigate to the directory of your python program.
2. start your program with: `python3 mindcuber-python.py` (maybe the python interpreter's name is `python` instead of `python3`)


Retry to do it in your preferred IDE. If this does not work, then (in the terminal cmd shell):

1.  `python3` (this starts python in interactive mode, also maybe `python` instead of `python3`)
2. in the interactive mode (prompt is `>>>`) do: `import ev3_dc`
3. in the interactive mode: `ev3_dc.__file__` (this shows the location of package ev3_dc)
4. go back to the cmd prompt with: `exit()`

Environment variable PYTHONPATH allows to add locations, where python packages can be located. Inform yourself about its usage and how to handle it in your preferred IDE.

Kind regards,
Christoph
