### ISSUE TITLE
No EV3 Device found!

### ISSUE THREAD

**Issue by JohnGrubba** [ChristophGaukel/ev3-python3#8]
I have my EV3 connected via USB to my PC and it still says No EV3 device found!
On the EV3 it shows me the USB Logo so i assume everything is correct!
Please help!

**Comment by Steve-Zheng** [comment]
Which OS do you use? For macOS it should work out of the box; For Windows and Linux you need to do install some USB backend to connect to EV3. Refer to [this doc](https://ev3-dc.readthedocs.io/en/latest/examples_ev3.html#connect-with-the-ev3-device) for details.

**Comment by JohnGrubba** [comment]
I will check it out! Thanks!

**Comment by JohnGrubba** [comment]
I got another Question! Can i also write a EV3 Program that uses the Messaging Block and somehow receive messages from it on my PC and send back information to the EV3? That would be great!

**Comment by ChristophGaukel** [comment]
sorry for my late reaction!
You want to run a program on your EV3-device, which reads and writes message blocks. On your PC you want to run another program, which also reads and writes message blocks. With this approach you will establish some communication between these two programs.
I have never done that and never felt the need to do it. When all the program logic runs on my PC, I have access on all data of the EV3 device. What is your motivation? Do you need it because of performance issues?
But why not? I expect, the direct commands opMailbox_... will do the job. But sorry, I have no experience.

Kind regards,
Christoph

**Comment by JohnGrubba** [comment]
I am also very late with that answer but i already made a Python Package for exactly that some while ago!
https://pypi.org/project/ev3msg/
